# Generated by Django 6.0.5 on 2026-05-12 12:39

import django.db.models.deletion
import django.utils.timezone
import titulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Área académica',
                'verbose_name_plural': 'Áreas académicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ceremonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField(default=2026)),
                ('lugar', models.CharField(default='Avenida Chile 1108', max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ceremonia',
                'verbose_name_plural': 'Ceremonias',
                'ordering': ['-anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloqueCeremonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('estado_registro', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('ceremonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='titulacion.ceremonia')),
            ],
            options={
                'verbose_name': 'Bloque de ceremonia',
                'verbose_name_plural': 'Bloques de ceremonia',
                'ordering': ['fecha', 'hora_inicio', 'nombre'],
                'unique_together': {('ceremonia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EstudianteTitulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('jornada', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_qr_estudiante', models.CharField(default=titulacion.models.generar_codigo_qr_estudiante, editable=False, max_length=255, unique=True)),
                ('imagen_qr_estudiante', models.ImageField(blank=True, null=True, upload_to='qr_estudiantes/')),
                ('ingreso_confirmado', models.BooleanField(default=False)),
                ('fecha_hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('invitaciones_entregadas', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bloque_ceremonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='titulacion.bloqueceremonia')),
            ],
            options={
                'verbose_name': 'Estudiante titulado',
                'verbose_name_plural': 'Estudiantes titulados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_invitacion', models.IntegerField()),
                ('codigo_qr', models.CharField(default=titulacion.models.generar_codigo_qr_invitacion, editable=False, max_length=255, unique=True)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='qr_invitaciones/')),
                ('usada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='titulacion.estudiantetitulado')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['estudiante__nombre_completo', 'numero_invitacion'],
                'unique_together': {('estudiante', 'numero_invitacion')},
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='titulacion.areaacademica')),
            ],
            options={
                'verbose_name': 'Plan de estudio',
                'verbose_name_plural': 'Planes de estudio',
                'ordering': ['area__nombre', 'nombre'],
                'unique_together': {('area', 'nombre', 'institucion')},
            },
        ),
        migrations.AddField(
            model_name='estudiantetitulado',
            name='plan_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='titulacion.planestudio'),
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('INVITADO', 'Invitado')], max_length=20)),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'Permitido'), ('DENEGADO', 'Denegado'), ('DUPLICADO', 'Duplicado'), ('ATRASADO', 'Atrasado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='titulacion.estudiantetitulado')),
                ('invitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='titulacion.invitacion')),
            ],
            options={
                'verbose_name': 'Registro de ingreso',
                'verbose_name_plural': 'Registros de ingreso',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='estudiantetitulado',
            unique_together={('rut', 'bloque_ceremonia', 'plan_estudio')},
        ),
    ]
