# Generated by Django 6.0.5 on 2026-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueceremonia',
            name='fecha_apertura_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloqueceremonia',
            name='fecha_cierre_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloqueceremonia',
            name='estado_registro',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='PROGRAMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroingreso',
            name='resultado',
            field=models.CharField(choices=[('PERMITIDO', 'Permitido'), ('DENEGADO', 'Denegado'), ('DUPLICADO', 'Duplicado'), ('ATRASADO', 'Atrasado'), ('OTRA_CEREMONIA', 'Otra ceremonia')], max_length=30),
        ),
    ]
