# Generated by Django 6.0.5 on 2026-05-15 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0002_bloqueceremonia_fecha_apertura_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioCeremonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('usuario_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bloque_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_destino', to='titulacion.bloqueceremonia')),
                ('bloque_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_origen', to='titulacion.bloqueceremonia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_ceremonia', to='titulacion.estudiantetitulado')),
            ],
            options={
                'verbose_name': 'Cambio de ceremonia',
                'verbose_name_plural': 'Cambios de ceremonia',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
