# Generated by Django 6.0 on 2026-06-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0004_bloqueceremonia_estado_cerrada_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantetitulado',
            name='detalle_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiantetitulado',
            name='motivo_no_asistencia',
            field=models.CharField(blank=True, choices=[('TRABAJO', 'Trabajo'), ('TURNO_LABORAL', 'Turno laboral'), ('VIAJE', 'Viaje'), ('PROBLEMAS_FAMILIARES', 'Problemas familiares'), ('PROBLEMAS_SALUD', 'Problemas de salud'), ('NO_INTERESA', 'No le interesa asistir'), ('FUERA_CIUDAD', 'Ya no reside en la ciudad'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiantetitulado',
            name='resultado_gestion',
            field=models.CharField(blank=True, choices=[('ENTREGADAS', 'Invitaciones entregadas'), ('CONFIRMA_ASISTENCIA', 'Estudiante confirma asistencia'), ('NO_ASISTIRA', 'Estudiante informa que no asistirá'), ('NO_CONTACTADO', 'No fue posible contactar'), ('PENDIENTE', 'Pendiente de confirmar'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
    ]
